Update Dockerfile

diff --git a/ttrss/Dockerfile b/ttrss/Dockerfile
--- a/ttrss/Dockerfile
+++ b/ttrss/Dockerfile
@@ -8,7 +8,6 @@ SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 # hadolint ignore=DL3003
 RUN \
 	apk add --no-cache \
-		nginx \
 		php7 \
 		php7-fpm \
 		php7-pdo \
@@ -42,6 +41,25 @@ RUN \
 		/usr/local/share/.cache \
 		/usr/lib/node_modules \
 		/var/www/ttrss/.git
+
+# https://github.com/caddyserver/caddy/releases
+ENV CADDY_VERSION 2.3.0
+
+# Install Caddy
+RUN set -eux; \
+	APKARCH="$(apk --print-arch)"; \
+	case "$APKARCH" in \
+		x86_64)  BINARCH='amd64' ;; \
+		armhf)   BINARCH='armv6' ;; \
+		armv7)   BINARCH='armv7' ;; \
+		aarch64) BINARCH='arm64' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+    curl -J -L -o /tmp/caddy.tar.gz "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_${BINARCH}.tar.gz"; \
+	tar zxvf /tmp/caddy.tar.gz -C /usr/bin caddy; \
+	chmod +x /usr/bin/caddy; \
+	rm -rf /tmp/caddy; \
+	caddy version
 
 # Copy root filesystem
 COPY rootfs /
